### ISSUE TITLE
Causes crashes during Hazard(world bam)

### ISSUE THREAD

**Issue by TerableCoder** [Risenio/fps-utils#3] opened 2019-06-29 01:13 UTC
When hazard uses its fear attack, it often crashes people using your fps-utils. About a 50% chance, but when it does crash users, it crashes all the users of your fork. This issue doesn't occur with the other fps-utils forks. I like yours better than theirs! Please fix.

**Comment by Risenio** [comment] 2019-06-29 09:36
Can you provide more details about the settings you had set when the crash occurred?
 - Optimization mode (0, 1, 2, 3)?
 - Summons (own, players)?

Which class do you play?
Any errors show up in the proxy log?

Also, is this new issue? Like e.g. You had no issues few days ago, but recently after some other module got updated and the issue started to occur afterward, or something? (If yes, you may wanna try use my fps-utils without that module, to see if it is the cause of crash or not).

---
P.s., I personally never had issue with it during the fights of any of the 3 Field bams.
People used to report similar issue with Tria guardian, where it when spawns the fear aoes and some hidden summoned NPC (thrall, st, totem) gets fear, it cause client crash, but that issue should be fixed by now.

**Comment by TerableCoder** [comment] 2019-06-29 21:04
Settings: https://cdn.discordapp.com/attachments/494032094310301716/594612089117736971/Untitled.png
It happens regardless of which class I play. It gives the proxy error of unstable module or unstable internet and instantly crashes the client. This issue has been around for months, but I just had it again a few days ago. I notice that it most frequently occurs when I'm late to the bam, aka not there when my raid starts initiates it, and in a raid of more than 5 people.

**Comment by Risenio** [comment] 2019-07-01 04:18
Alright, I had run some tests the last 2 days, and it seems I can't reproduce the issue.
So I was guessing that it might be region-related issue? as it happened before for another NPC for NA region.

I can't really figure out how to deal with that (as I can't reproduce it), but when you said `it crashes all the users of your fork`, Are you that certain it's only from my fork? it doesn't like crash other players too? (I mean people who are not using any scripts or so).

Regarding `most frequently occurs when I'm late to the bam` or `in a raid of more than 5 people` parts, that might be irrelevant, just saying.

Now, I don't know if it's a big thing to ask, but you may help by providing packet logs for me (Like you run logger and go do the field bam, and once you crash at that fear mechanic, you give me the log), so that way I may be able to identify which packet might be responsible for that, but that's up to you, of course.

**Comment by TerableCoder** [comment] 2019-07-01 04:23
My friend and I use your fps-utils and when I crash, he also crashes, but no one else doing the bam does. He switched to codeagon's fps-utils and now he doesn't crash when I crash, I'm the only person who crashes now. 

I'll run a packet logger the next time I do the bam. Thanks!

**Comment by Risenio** [comment] 2019-07-12 07:19
So, Does your client still crashes during the Hazard FBam? or it stopped to occur after the latest NA patch?

**Comment by TerableCoder** [comment] 2019-07-12 07:20
I think FPS-booster was the problem, I haven't done enough Hazard to confirm this yet.

**Comment by Risenio** [comment] 2019-07-16 11:22
Seems like this issue ain't occuring anymore, hence I'll close this for now.

**Closed as completed by Risenio** 2019-07-16 11:22 UTC
Labels: Possible Bug
