### ISSUE TITLE
Hiding summons makes ShinraMeter not record damage done by thralls on mystic

### ISSUE THREAD

**Issue by kirabera** [Risenio/fps-utils#8] opened 2020-01-11 04:08 UTC
as titled.

**Comment by Risenio** [comment] 2020-01-14 17:52
Hello.

I've tried to re-produce this issue, but I couldn't.
I have tried hiding my own thralls and checking damage, it still counts.
I also tried hiding other's thralls, and checking damage, it also counted.

So let me ask you some couple of questions, regarding that, so I can reproduce it.
Do you use proxy or toolbox?
Also which region do you play on?
And lastly, Do you use some kind of vpn? (if so, specify which one).

Also does this issue occur for your own thralls or other player's ones?

**Comment by Risenio** [comment] 2020-01-30 13:03
Hey there.

I've did some investigations trying to see if anyone has got this issue before, and seems a couple of people did, and that has occurred from the wrong configuration of their VPN, so if you're using one, make sure you configuration it properly (by excluding `tera.exe` from VPN config), and if the issue still occurs, reopen this issue with providing more information on how to produce it.

I'll be closing this issue due to lack of information provided, and miscommunication.

**Closed as completed by Risenio** 2020-01-30 13:03 UTC
Labels: Invalid
